#include "windows.h"

#ifndef CONSOLE_COLOR_H
#define CONSOLE_COLOR_H

#define BACKGROUND_PURPLE BACKGROUND_BLUE | BACKGROUND_RED
#define BACKGROUND_CYAN BACKGROUND_BLUE | BACKGROUND_GREEN
#define BACKGROUND_YELLOW BACKGROUND_RED | BACKGROUND_GREEN
#define BACKGROUND_WHITE BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_GREEN
#define BACKGROUND_BLACK 0
#define BACKGROUND_PINK BACKGROUND_RED | BACKGROUND_INTENSITY
#define BACKGROUND_LIGHTGREEN BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define BACKGROUND_LIGHTBLUE BACKGROUND_BLUE | BACKGROUND_INTENSITY
#define BACKGROUND_LIGHTPURPLE BACKGROUND_PURPLE | BACKGROUND_INTENSITY
#define BACKGROUND_LIGHTCYAN BACKGROUND_CYAN | BACKGROUND_INTENSITY
#define BACKGROUND_LIGHTYELLOW BACKGROUND_YELLOW | BACKGROUND_INTENSITY
#define BACKGROUND_LIGHTWHITE BACKGROUND_WHITE | BACKGROUND_INTENSITY
#define BACKGROUND_GREY BACKGROUND_BLACK | BACKGROUND_INTENSITY

struct CONSOLE_COLOR
{
    unsigned char red;
    unsigned char green;
    unsigned char blue;

    WORD flags;
};

int colorDifference(unsigned char red, unsigned char green, unsigned char blue, struct CONSOLE_COLOR cc);

WORD closestColor(unsigned char red, unsigned char green, unsigned char blue);

#endif